var argusStatsConstructor=function(z){var d=[],n=0,p=0,e,l,f,g;var q=g=f=l=e=!1;var c=null,k={},r=function(){console.debug("send event to wetest ");var a=JSON.stringify(d),b={testid:c.testid,deviceid:c.deviceid,data:a,req_index:p};console.debug("clear event cache before send");d=[];var m={};"undefined"!=typeof c.sessionid?m.Cookie=c.sessionid:console.log("sessionid invalid "+c.sessionid);"undefined"!=typeof c.token&&"undefined"!=typeof c.time?(b.token=c.token,b.time=c.time):console.log("token or time invalid ,"+
c.token+","+c.time);wx.request({url:argusStatsConstructor.WETEST_EVENT_API_URL,data:b,method:"POST",header:m,success:function(b){p+=1;console.log("wetest api request success");!0===b.data.flag?console.log("wetest miniappEvent api success"):(console.log("wetest miniappEvent api error, msg:"+b.data.msg),wx.showToast({title:"wetest miniappEvent api error, msg:"+b.data.msg,icon:"none",duration:3E3}),console.log("parse event cache from json string"),b=JSON.parse(a),d=d.concat(b),console.debug(d))},fail:function(b){console.log("wetest miniappEvent api request fail");
wx.showToast({title:"wetest miniappEvent api request fail",icon:"none",duration:3E3});console.log("parse event cache from json string");b=JSON.parse(a);d=d.concat(b);console.debug(d)}})},t=function(){wx.request({url:argusStatsConstructor.WETEST_EVENT_API_URL,method:"GET",success:function(a){console.log("wetest api request success");wx.showModal({title:"wetest\u767d\u540d\u5355\u68c0\u6d4b",content:"\u5df2\u6dfb\u52a0wetest\u767d\u540d\u5355",showCancel:!1})},fail:function(a){console.log("wetest api request fail");
wx.showModal({title:"wetest\u767d\u540d\u5355\u68c0\u6d4b",content:"\u672a\u6dfb\u52a0wetest\u767d\u540d\u5355\uff0c\u8bf7\u63d0\u9192\u5f00\u53d1\u914d\u7f6e",showCancel:!1})}})},u=function(a){console.log("check wether event is first load ");!1===q&&f&&(a.is_firstload_flag=g,q=!0,console.log("set event firstload flag"));!1===l&&"Page"===a.event_type&&"onReady"===a.event_name&&(l=a.first_onReady_flag=!0,console.log("found first page onready"))},h=function(a){u(a);n+=1;a.g_event_cnt=n;d.push(a);!1===
e?console.log("clipboard has not ready, return"):null===c?console.log("clipboard format error. can not send data to wetest"):(d.sort(function(b,a){return b.g_event_cnt-a.g_event_cnt}),console.debug("after sort of "),console.debug(d),r())},v=function(){var a=App;App=function(){var b=0,c=arguments[0].onLaunch;arguments[0].onLaunch=function(){var a=Date.now();b+=1;h({event_type:"App",event_name:"onLaunch",event_index:b,timestamp:a,page_path:"",page_title:""});if(c)return c.apply(this,[].slice.call(arguments))};
var d=arguments[0].onShow;arguments[0].onShow=function(){var a=Date.now();h({event_type:"App",event_name:"onShow",event_index:b,timestamp:a,page_path:"",page_title:""});if(d)return d.apply(this,[].slice.call(arguments))};var e=arguments[0].onHide;arguments[0].onHide=function(){var a=Date.now();h({event_type:"App",event_name:"onHide",event_index:b,timestamp:a,page_path:"",page_title:""});if(e)return e.apply(this,[].slice.call(arguments))};if(a)return a.apply(this,[].slice.call(arguments))}},w=function(){var a=
Page;Page=function(){var b=0,c=arguments[0].onLoad;arguments[0].onLoad=function(){var a=Date.now();b+=1;k[this.route]="undefined"!=typeof __wxConfig.page[this.route+".html"]&&"undefined"!=typeof __wxConfig.page[this.route+".html"].window&&"undefined"!=typeof __wxConfig.page[this.route+".html"].window.navigationBarTitleText?__wxConfig.page[this.route+".html"].window.navigationBarTitleText:"";h({event_type:"Page",event_name:"onLoad",event_index:b,timestamp:a,page_path:this.route,page_title:k[this.route]});
if(c)return c.apply(this,[].slice.call(arguments))};var d=arguments[0].onShow;arguments[0].onShow=function(){var a=Date.now();h({event_type:"Page",event_name:"onShow",event_index:b,timestamp:a,page_path:this.route,page_title:k[this.route]});if(d)return d.apply(this,[].slice.call(arguments))};var e=arguments[0].onReady;arguments[0].onReady=function(){var a=Date.now();h({event_type:"Page",event_name:"onReady",event_index:b,timestamp:a,page_path:this.route,page_title:k[this.route]});if(e)return e.apply(this,
[].slice.call(arguments))};var f=arguments[0].onHide;arguments[0].onHide=function(){var a=Date.now();h({event_type:"Page",event_name:"onHide",event_index:b,timestamp:a,page_path:this.route,page_title:k[this.route]});if(f)return f.apply(this,[].slice.call(arguments))};var g=arguments[0].onUnload;arguments[0].onUnload=function(){var a=Date.now();h({event_type:"Page",event_name:"onUnload",event_index:b,timestamp:a,page_path:this.route,page_title:k[this.route]});if(g)return g.apply(this,[].slice.call(arguments))};
if(a)return a.apply(this,[].slice.call(arguments))}},x=function(){var a=wx.setNavigationBarTitle,b=function(){var b=getCurrentPages(),b=b[b.length-1],c=arguments[0].title;"undefined"!=typeof b&&"undefined"!=typeof c&&"undefined"!=typeof b.route&&(k[b.route]=c);if(a)return a.apply(this,[].slice.call(arguments))};Object.defineProperty(wx,"setNavigationBarTitle",{get:function(){return b}})},y=function(){console.log("get_clipboard_cmd called "+Date.now());e=!1;c=null;wx.getClipboardData({success:function(a){console.log("clipboard: "+
a.data.substr(0,10)+" "+Date.now());var b=a.data.split("::");if(2===b.length&&"[wetest_miniapp_test]"===b[0]&&b[1])try{c=JSON.parse(b[1]),"undefined"!=typeof c.testid&&"undefined"!=typeof c.deviceid&&("undefined"!=typeof c.sessionid&&(e=!0),"undefined"!=typeof c.token&&"undefined"!=typeof c.time&&(e=!0))}catch(m){e=!1,wx.showModal({title:"\u4ece\u526a\u8d34\u677f\u4e2d\u89e3\u6790json\u5931\u8d25:",content:a.data,showCancel:!1})}!1===e&&wx.showModal({title:"\u65e0\u6cd5\u4ece\u526a\u8d34\u677f\u4e2d\u83b7\u5f97\u6b63\u786e\u4fe1\u606f:",
content:a.data,showCancel:!1})},fail:function(a){wx.showModal({title:"\u65e0\u6cd5\u4ece\u526a\u8d34\u677f\u4e2d\u83b7\u5f97\u6b63\u786e\u4fe1\u606f:",content:"\u65e0\u6cd5\u4ece\u526a\u8d34\u677f\u4e2d\u83b7\u5f97\u6b63\u786e\u4fe1\u606f",showCancel:!1})}})};return{start:function(){console.log("argus stats start");t();y();var a=wx.getFileSystemManager();try{a.mkdirSync(wx.env.USER_DATA_PATH+"/argus_dir"),g=f=!0}catch(b){wx.getStorageSync("argus_is_firstload")?(f=!0,g=!1):(g=f=!0,wx.setStorageSync("argus_is_firstload",
!0))}v();w();x()}}};argusStatsConstructor.EVENT_CACHESIZE=100;argusStatsConstructor.WETEST_EVENT_API_URL="https://wetest.qq.com/cloud/api/miniappEvent";var argusStats=argusStatsConstructor();argusStats.start();module.exports={argusStats:argusStatsConstructor};
